### ISSUE TITLE
Kraken Issue

### ISSUE THREAD

**Issue by kieffer-reitenbach** [kieffer-reitenbach/kraken-good-accessibility#2]
@wendywarren

Everything on markbot was good to go, the only thing was that "nav-hover" section at the bottom that won't load. I hope the rest is okay.
Thank you!

**Comment by wendywarren** [comment]
Hi @kieffer-reitenbach,

The majority of your assignment is done properly. There are just a few areas I'll give you feedback on. 

You've assigned the role of main to the article but in this case, within the article, the div with all of the <p> content would be considered the main piece of content a user may want to jump to.

For the footer navigation you'll want to replace the html for the svg from:
`<svg><use xlink:href="images/icons.svg#prev"></use></svg>`

To this:
`<img src="images/icons-prev.svg" alt="previous icon">`

Of course changing the icon image itself and the alt attribute description. This wasn't your mistake but an adjustment to the original code in the assignment to make icons appear.

Also in the footer nav, you'll want to replace the aria-label="#' on each link with a short description of where this link is taking you. Example: "Go to previous chapter"

Hope that helps!
Wendy
